### PR TITLE
Add support for analyze and genmove_analyze [Draft].

### PR DESCRIPTION
**Pull request by CGLemon**
Add support for ```lz-analyze``` and ```lz-genmove_analyze```.  Will add support for ```cgos-analyze``` and ```cgos-genmove_analyze``` in order to support for #50 .

## DONE
* Add support for ```lz-analyze``` and ```lz-genmove_analyze```.
* Add support for  ```cgos-analyze``` and ```cgos-genmove_analyze```.
* Work well on the Sabaki.
* Test on CGOS.
* Add support for PV.

## TODO
* Fix the code style.

### CODE REVIEW

**Comment by CGLemon** [comment]
May you add the PV function in the ```MCTSNode```? The full analysis function needs the PV.

**Comment by kobanium** [comment]
Thanks for your great contributions. I don't understand these analyze commands well, so your work helps me greatly.
I have implemented the PV function for now, but you can modify it to make it easier for you. This is already merged to the develop branch.
MR #60

**Comment by CGLemon** [comment]
Already test this branch on the CGOS. Here is the SGF.

http://www.yss-aya.com/cgos/viewer.cgi?9x9/SGF/2023/06/07/1440373.sgf

**Comment by CGLemon** [comment]
But look like the PV is strange.

Here is the PV showed by TamaGo.
Screenshot from 2023-06-08 00-46-37

Here is the search map after playing this move.
Screenshot from 2023-06-08 00-46-51

I have no ideal what happened? Are you sure that tree search is correct? Or maybe there is a bug in ```get_best_move_sequence()```.

**Comment by kobanium** [comment]
Which did you use sl-model.bin or rl-model.bin?
I think this phenomenon is possible if you are using sl-model.bin, because non root nodes temporarily use Policy with random values until neural network calculations are done. As far as I checked, there doesn't seem to be a problem, so I'm thinking of merging this branch into the develop branch. What do you think?

**Comment by CGLemon** [comment]
I used the ```rl-model.bin``` but I found the same problem when using  ```sl-model.bin```. The PV string is not just weird. There are even illegal moves in the PV string. I think it is necessary to check this bug. I have no idea about it. I  only sure that it is not bug of analyze command. You may merge the branch if you think the code style is OK. And fix another issue on new branch.

I think you may want to add the Japanese command. Here are all functions which I changed or added. It may help you to add the command.

1. at the gtp/client.py

```
def _analyze(self, mode: str, arg_list: List[str]) -> NoReturn:
def _genmove_analyze(self, mode: str, arg_list: List[str]) -> int:
```

* ```mode```: Select the analysis command. Must be ```lz``` or ```cgos```.


2. at the mcts/node

```
def get_analysis(self, board: GoBoard, mode: str, pv_lists_func) -> str:
```

* ```mode```: Must be ```lz``` or ```cgos```.
* ```pv_lists_func```: It is PV function which is ```get_pv_lists()```.


3. at the mcts/tree

```
def search_best_move(self, board: GoBoard, color: Stone, time_manager: TimeManager, \
    analysis_query: Dict = dict()) -> int:
def ponder(self, board: GoBoard, color: Stone, analysis_query: Dict) -> NoReturn:
def search(self, board: GoBoard, color: Stone, time_manager: TimeManager, \
    analysis_query: Dict) -> NoReturn:
```

* ```analysis_query```: Send the analysis command via it. It should be empty if we don't analyze the game.

4. at the mcts/tree

```
def get_pv_lists(self, root, coord: Coordinate) -> Dict[str, List[str]]:
```

* ```root```: Get the PV string since this node.

Thanks!

**Comment by kobanium** [comment]
I find a bug. As you mentioned, it is the bug of```get_best_move_sequence```.
I call this function,
```
pv_list = self.get_best_move_sequence([root.action[i]], i)
```
it should be
```
pv_list = self.get_best_move_sequence([root.action[i]], root.children_index[i])
```
Thanks.

**Pull request merged**
